### ISSUE TITLE
x-studio-10.0.9000.2X release checklist

### ISSUE THREAD

**Issue by halx99** [simdsoft/x-studio#782]
- [x] Active account of https://open.soft.360.cn/
- [x] Upgrade Luacheck to 0.24.0 should works
- [x] New lua-compile.bat command line documentation
- [x] 3d csb recovery should works
- [x] csb 2.0 should works
- [x] csb 1.9 (protobuf) should works
- [x] Other software compatible when use cocos2d-x-4.0
- [x] Scintilla 5.x
- [ ] English website
- [ ] Publish online Paypal
- [ ] English download site
